--------------------------------------------------------
--  DDL for Table STUDENT_MARKS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STUDENT_MARKS" 
   (	"MARK_ID" NUMBER, 
	"STUDENT_ID" NUMBER, 
	"SUBJECT_NAME" VARCHAR2(50 BYTE), 
	"MARKS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008261
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008261" ON "SYSTEM"."STUDENT_MARKS" ("MARK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table STUDENT_MARKS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STUDENT_MARKS" ADD PRIMARY KEY ("MARK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT_MARKS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STUDENT_MARKS" ADD CONSTRAINT "STUDENT_MARKS_FK" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SYSTEM"."STUDENT" ("ID") ENABLE;
